Repository matplotlib/napari-matplotlib, pull requests merged in 2024-01, with the labels that each got.

#198 Add contrast limits to histogram plot
  src/napari_matplotlib/histogram.py
Labels: New feature, Changelog needed

#245 Add a features histogram example
  examples/features_hist.py
Labels: Docs, Changelog needed

#237 Theme detection and update improvements
  MANIFEST.in
  docs/user_guide.rst
  pyproject.toml
  src/napari_matplotlib/base.py
  src/napari_matplotlib/styles/README.md
  src/napari_matplotlib/styles/dark.mplstyle
  src/napari_matplotlib/styles/light.mplstyle
  src/napari_matplotlib/tests/baseline/test_custom_theme.png
  src/napari_matplotlib/tests/baseline/test_feature_histogram_points.png
  src/napari_matplotlib/tests/baseline/test_feature_histogram_vectors.png
  src/napari_matplotlib/tests/baseline/test_histogram_2D.png
  src/napari_matplotlib/tests/baseline/test_histogram_3D.png
  src/napari_matplotlib/tests/baseline/test_slice_2D.png
  src/napari_matplotlib/tests/baseline/test_slice_3D.png
  src/napari_matplotlib/tests/data/test_theme.mplstyle
  src/napari_matplotlib/tests/scatter/baseline/test_features_scatter_widget_2D.png
  src/napari_matplotlib/tests/scatter/baseline/test_scatter_2D.png
  src/napari_matplotlib/tests/scatter/baseline/test_scatter_3D.png
  src/napari_matplotlib/tests/test_theme.py
  src/napari_matplotlib/util.py
Labels: New feature

#244 Use integer bins for integer data in `HistogramWidget`
  docs/changelog.rst
  src/napari_matplotlib/histogram.py
  src/napari_matplotlib/tests/baseline/test_histogram_2D.png
  src/napari_matplotlib/tests/baseline/test_histogram_3D.png
Labels: New feature, Changelog needed

#246 Add changelog for 2.0
  docs/changelog.rst
Labels: Docs

#250 Ensure `HistogramWidget` always uses 100 bins by default
  src/napari_matplotlib/histogram.py
  src/napari_matplotlib/tests/baseline/test_feature_histogram_points.png
  src/napari_matplotlib/tests/baseline/test_feature_histogram_vectors.png
Labels: Changelog needed

#252 Fix HistogramWidget for multiscale data
  pyproject.toml
  src/napari_matplotlib/histogram.py
Labels: Changelog needed

#253 Add 2.0.1 changelog
  docs/changelog.rst
Labels: Docs
